import fs from 'node:fs';
import path from 'node:path';
import {createHash,timingSafeEqual} from 'node:crypto';
import webpush from 'web-push';

const allowedOrigins=new Set(['https://svenskaxcvi.github.io','https://daylight-mobile-app.onrender.com']);
export function validPushSubscription(subscription){try{const u=new URL(subscription.endpoint);const host=u.hostname;return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&(host.endsWith('.push.apple.com')||host==='fcm.googleapis.com'||host==='updates.push.services.mozilla.com'||host.endsWith('.notify.windows.com'))&&Buffer.from(subscription.keys?.p256dh||'','base64url').length===65&&Buffer.from(subscription.keys?.auth||'','base64url').length===16;}catch{return false}}
export function normalizeJobs(jobs,now=Date.now()){return [...new Map((Array.isArray(jobs)?jobs:[]).slice(0,1200).filter(j=>typeof j.id==='string'&&j.id.length<150&&Number.isFinite(j.dueAt)&&j.dueAt>now-120000&&j.dueAt<now+91*86400000&&j.targetAt-j.dueAt===600000&&['leave','pickup'].includes(j.kind)&&/^\d{4}-\d{2}-\d{2}$/.test(j.date)).map(j=>[j.id,{id:j.id,dueAt:j.dueAt,targetAt:j.targetAt,title:String(j.title||'School reminder').slice(0,160),body:String(j.body||'').slice(0,250),date:j.date,kind:j.kind}])).values()]}
export async function deliverDueJobs(records,send,now=Date.now()){
 for(const [id,record] of Object.entries(records)){for(const job of record.jobs||[]){if(record.sent[job.id]||job.dueAt>now)continue;if(now-job.dueAt>120000){record.sent[job.id]=now;continue}try{await send(record.subscription,JSON.stringify({title:job.title,body:job.body,tag:`daylight-${job.id}`,date:job.date,kind:job.kind}),{urgency:'high',TTL:120,timeout:10000});record.sent[job.id]=now;}catch(error){if([404,410].includes(error.statusCode)){delete records[id];break;}}}record.jobs=record.jobs.filter(j=>!record.sent[j.id]);record.sent=Object.fromEntries(Object.entries(record.sent).filter(([,time])=>now-time<91*86400000));}
}
export function createPushService({dataDir=process.env.DAYLIGHT_PUSH_DATA_DIR,roomExists,readJson}){
 let available=false,keys,records={},file,ticking=false;
 if(dataDir){try{fs.mkdirSync(dataDir,{recursive:true,mode:0o700});file=path.join(dataDir,'push-devices.json');const keyFile=path.join(dataDir,'vapid-private.json');keys=fs.existsSync(keyFile)?JSON.parse(fs.readFileSync(keyFile,'utf8')):webpush.generateVAPIDKeys();if(!fs.existsSync(keyFile))fs.writeFileSync(keyFile,JSON.stringify(keys),{mode:0o600});records=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{};webpush.setVapidDetails('https://svenskaxcvi.github.io/Daylight/',keys.publicKey,keys.privateKey);available=true;}catch{console.error('Background reminders unavailable: check persistent data directory.')}}
 const persist=()=>{const temp=file+'.next';fs.writeFileSync(temp,JSON.stringify(records),{mode:0o600});fs.renameSync(temp,file)};
 const reply=(res,status,value)=>{res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':res.daylightPushOrigin||'https://svenskaxcvi.github.io','vary':'Origin','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(value))};
 const equal=(a,b)=>{const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&timingSafeEqual(x,y)};
 async function handle(req,res){const route=req.url?.split('?')[0];if(!route?.startsWith('/api/push/'))return false;res.daylightPushOrigin=allowedOrigins.has(req.headers.origin)?req.headers.origin:null;if(req.headers.origin&&!allowedOrigins.has(req.headers.origin)){reply(res,403,{error:'Origin not allowed'});return true}if(req.method==='OPTIONS'){reply(res,204,{});return true}if(route==='/api/push/config'&&req.method==='GET'){reply(res,200,{available,publicKey:available?keys.publicKey:null});return true}if(!available){reply(res,503,{error:'Background reminders need always-on hosting with persistent storage.'});return true}if(req.method!=='POST'){reply(res,405,{error:'Method not allowed'});return true}
  try{const body=await readJson(req,300000),roomId=String(body.roomId||''),deviceId=String(body.deviceId||''),token=String(body.token||'');if(!/^[a-f0-9]{64}$/.test(roomId)||!deviceId||deviceId.length>100||!/^[a-f0-9]{64}$/.test(token)){reply(res,400,{error:'Invalid device registration'});return true}const id=createHash('sha256').update(roomId+'|'+deviceId).digest('hex'),record=records[id];if(record&&!equal(record.token,token)){reply(res,403,{error:'Device authorization failed'});return true}if(!record&&!roomExists(roomId)){reply(res,403,{error:'Connect this device to your family first'});return true}
   if(route==='/api/push/unsubscribe'){delete records[id];persist();reply(res,200,{enabled:false});return true}
   if(route!=='/api/push/schedule'){reply(res,404,{error:'Not found'});return true}if(!validPushSubscription(body.subscription)){reply(res,400,{error:'Invalid push subscription'});return true}if(!record&&Object.keys(records).length>=500){reply(res,503,{error:'Reminder capacity reached'});return true}records[id]={roomId,token,subscription:body.subscription,jobs:normalizeJobs(body.jobs),sent:record?.sent||{},updatedAt:Date.now()};persist();reply(res,200,{enabled:true,scheduled:records[id].jobs.length});
  }catch{reply(res,400,{error:'Could not save notification schedule'});}return true;
 }
 const timer=available?setInterval(async()=>{if(ticking)return;ticking=true;try{await deliverDueJobs(records,(...args)=>webpush.sendNotification(...args));persist()}catch{console.error('Background reminder delivery failed')}finally{ticking=false}},15000):null;timer?.unref();return {handle,available,close:()=>timer&&clearInterval(timer)};
}


